# Generated by Django 5.2.17 on 2026-08-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feature_bullets',
            field=models.JSONField(blank=True, default=list, help_text='Key features as bullet points'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief 1-sentence summary for cards (max 160 chars)', max_length=500),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Image file (JPG, PNG, WebP recommended)', upload_to='projects/gallery/%Y/%m/')),
                ('image_type', models.CharField(choices=[('detail', 'Detail Page'), ('preview', 'Card Preview'), ('gallery', 'Gallery')], default='gallery', help_text='Category of image', max_length=10)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility and SEO', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Optional caption shown with image', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in gallery')),
                ('is_featured', models.BooleanField(default=False, help_text='If True and type is preview, this becomes the card preview')),
                ('project', models.ForeignKey(help_text='The project this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ('display_order', '-created_at'),
                'unique_together': {('project', 'image')},
            },
        ),
    ]
